/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TodoInterface extends Interface {
    getFunction(nameOrSignature: "createTodo" | "markAsDone" | "updateTodo"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MarkTodoAsDone" | "TodoCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createTodo', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'markAsDone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateTodo', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createTodo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markAsDone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTodo', data: BytesLike): Result;
  }

  
    export namespace MarkTodoAsDoneEvent {
      export type InputTuple = [text: string, status: BigNumberish];
      export type OutputTuple = [text: string, status: bigint];
      export interface OutputObject {text: string, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TodoCreatedEvent {
      export type InputTuple = [text: string, deadline: BigNumberish];
      export type OutputTuple = [text: string, deadline: bigint];
      export interface OutputObject {text: string, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Todo extends BaseContract {
    
    connect(runner?: ContractRunner | null): Todo;
    waitForDeployment(): Promise<this>;

    interface: TodoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createTodo: TypedContractMethod<
      [_text: string, _deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    markAsDone: TypedContractMethod<
      [_id: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    updateTodo: TypedContractMethod<
      [_id: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createTodo'): TypedContractMethod<
      [_text: string, _deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'markAsDone'): TypedContractMethod<
      [_id: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTodo'): TypedContractMethod<
      [_id: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'MarkTodoAsDone'): TypedContractEvent<MarkTodoAsDoneEvent.InputTuple, MarkTodoAsDoneEvent.OutputTuple, MarkTodoAsDoneEvent.OutputObject>;
getEvent(key: 'TodoCreated'): TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;

    filters: {
      
      'MarkTodoAsDone(string,uint8)': TypedContractEvent<MarkTodoAsDoneEvent.InputTuple, MarkTodoAsDoneEvent.OutputTuple, MarkTodoAsDoneEvent.OutputObject>;
      MarkTodoAsDone: TypedContractEvent<MarkTodoAsDoneEvent.InputTuple, MarkTodoAsDoneEvent.OutputTuple, MarkTodoAsDoneEvent.OutputObject>;
    

      'TodoCreated(string,uint256)': TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;
      TodoCreated: TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;
    
    };
  }