/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'Add', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Add__factory>
getContractFactory(name: 'Average', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Average__factory>
getContractFactory(name: 'Todo', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Todo__factory>

  getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'Add', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Add>
getContractAt(name: 'Average', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Average>
getContractAt(name: 'Todo', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Todo>

  deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'Add', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Add>
deployContract(name: 'Average', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Average>
deployContract(name: 'Todo', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Todo>

  deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'Add', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Add>
deployContract(name: 'Average', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Average>
deployContract(name: 'Todo', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Todo>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  