/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as todoSol from './Todo.sol/index.js';
export type { todoSol };
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export type { Add } from './Todo.sol/Add.js';
export { Add__factory } from './factories/Todo.sol/Add__factory.js';
export type { Average } from './Todo.sol/Average.js';
export { Average__factory } from './factories/Todo.sol/Average__factory.js';
export type { Todo } from './Todo.sol/Todo.js';
export { Todo__factory } from './factories/Todo.sol/Todo__factory.js';