/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionSol from './auction.sol/index.js';
export type { auctionSol };
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export type { AuctionContract } from './auction.sol/AuctionContract.js';
export { AuctionContract__factory } from './factories/auction.sol/AuctionContract__factory.js';