/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AuctionContractInterface extends Interface {
    getFunction(nameOrSignature: "auctionCounter" | "auctions" | "bid" | "createAuction" | "endAuction" | "refundBidders" | "refunds" | "refundsGetterFunction" | "startAuction"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionInitialaized"): EventFragment;

    encodeFunctionData(functionFragment: 'auctionCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'bid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuction', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'endAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'refundBidders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'refunds', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'refundsGetterFunction', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'startAuction', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'auctionCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundBidders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundsGetterFunction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startAuction', data: BytesLike): Result;
  }

  
    export namespace AuctionInitialaizedEvent {
      export type InputTuple = [id: BigNumberish];
      export type OutputTuple = [id: bigint];
      export interface OutputObject {id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AuctionContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): AuctionContract;
    waitForDeployment(): Promise<this>;

    interface: AuctionContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    auctionCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, string, string, bigint, bigint, bigint] & {id: bigint, startingPrice: bigint, status: bigint, owner: string, highestBidder: string, highestBid: bigint, startTime: bigint, duration: bigint }],
      'view'
    >
    

    
    bid: TypedContractMethod<
      [auction_id: BigNumberish, ],
      [boolean],
      'payable'
    >
    

    
    createAuction: TypedContractMethod<
      [_price: BigNumberish, _duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    endAuction: TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    refundBidders: TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    refunds: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    refundsGetterFunction: TypedContractMethod<
      [_id: BigNumberish, addr: AddressLike, ],
      [void],
      'view'
    >
    

    
    startAuction: TypedContractMethod<
      [_auctionsId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'auctionCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, string, string, bigint, bigint, bigint] & {id: bigint, startingPrice: bigint, status: bigint, owner: string, highestBidder: string, highestBid: bigint, startTime: bigint, duration: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'bid'): TypedContractMethod<
      [auction_id: BigNumberish, ],
      [boolean],
      'payable'
    >;
getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [_price: BigNumberish, _duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refundBidders'): TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refunds'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refundsGetterFunction'): TypedContractMethod<
      [_id: BigNumberish, addr: AddressLike, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'startAuction'): TypedContractMethod<
      [_auctionsId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuctionInitialaized'): TypedContractEvent<AuctionInitialaizedEvent.InputTuple, AuctionInitialaizedEvent.OutputTuple, AuctionInitialaizedEvent.OutputObject>;

    filters: {
      
      'AuctionInitialaized(uint256)': TypedContractEvent<AuctionInitialaizedEvent.InputTuple, AuctionInitialaizedEvent.OutputTuple, AuctionInitialaizedEvent.OutputObject>;
      AuctionInitialaized: TypedContractEvent<AuctionInitialaizedEvent.InputTuple, AuctionInitialaizedEvent.OutputTuple, AuctionInitialaizedEvent.OutputObject>;
    
    };
  }