/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface NFTmarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "buyNFT" | "cancelListing" | "feePercentage" | "listNFT" | "listings" | "owner" | "setFeePercentage" | "treasury"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ItemBought" | "ItemListed" | "ListingCancelled"): EventFragment;

    encodeFunctionData(functionFragment: 'buyNFT', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feePercentage', values?: undefined): string;
encodeFunctionData(functionFragment: 'listNFT', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'listings', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFeePercentage', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buyNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feePercentage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeePercentage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  }

  
    export namespace ItemBoughtEvent {
      export type InputTuple = [buyer: AddressLike, nftAddress: AddressLike, tokenId: BigNumberish, price: BigNumberish];
      export type OutputTuple = [buyer: string, nftAddress: string, tokenId: bigint, price: bigint];
      export interface OutputObject {buyer: string, nftAddress: string, tokenId: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemListedEvent {
      export type InputTuple = [seller: AddressLike, nftAddress: AddressLike, tokenId: BigNumberish, price: BigNumberish];
      export type OutputTuple = [seller: string, nftAddress: string, tokenId: bigint, price: bigint];
      export interface OutputObject {seller: string, nftAddress: string, tokenId: bigint, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListingCancelledEvent {
      export type InputTuple = [seller: AddressLike, nftAddress: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [seller: string, nftAddress: string, tokenId: bigint];
      export interface OutputObject {seller: string, nftAddress: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NFTmarketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): NFTmarketplace;
    waitForDeployment(): Promise<this>;

    interface: NFTmarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyNFT: TypedContractMethod<
      [nftAddress: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    cancelListing: TypedContractMethod<
      [nftAddress: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feePercentage: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    listNFT: TypedContractMethod<
      [nftAddress: AddressLike, tokenId: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    listings: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[string, bigint] & {seller: string, price: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setFeePercentage: TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyNFT'): TypedContractMethod<
      [nftAddress: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [nftAddress: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feePercentage'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'listNFT'): TypedContractMethod<
      [nftAddress: AddressLike, tokenId: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listings'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[string, bigint] & {seller: string, price: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setFeePercentage'): TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ItemBought'): TypedContractEvent<ItemBoughtEvent.InputTuple, ItemBoughtEvent.OutputTuple, ItemBoughtEvent.OutputObject>;
getEvent(key: 'ItemListed'): TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
getEvent(key: 'ListingCancelled'): TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;

    filters: {
      
      'ItemBought(address,address,uint256,uint256)': TypedContractEvent<ItemBoughtEvent.InputTuple, ItemBoughtEvent.OutputTuple, ItemBoughtEvent.OutputObject>;
      ItemBought: TypedContractEvent<ItemBoughtEvent.InputTuple, ItemBoughtEvent.OutputTuple, ItemBoughtEvent.OutputObject>;
    

      'ItemListed(address,address,uint256,uint256)': TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
      ItemListed: TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
    

      'ListingCancelled(address,address,uint256)': TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
      ListingCancelled: TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
    
    };
  }