/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Extended } from './IERC20Extended.js';
export type { Ownable } from './Ownable.js';
export type { StakingPool } from './StakingPool.js';