/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface StakingPoolInterface extends Interface {
    getFunction(nameOrSignature: "claimRewards" | "earlyWithdrawalPenalty" | "earned" | "emergencyWithdraw" | "emergencyWithdrawEnabled" | "exit" | "fundRewards" | "getPoolInfo" | "getUserInfo" | "lastUpdateTime" | "lockPeriod" | "owner" | "pendingRewards" | "poolId" | "rewardPerToken" | "rewardPerTokenStored" | "rewardRate" | "rewardToken" | "setEmergencyWithdrawEnabled" | "setLockPeriod" | "setPenalty" | "setRewardRate" | "stake" | "stakingToken" | "totalStaked" | "transferOwnership" | "userInfo" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EmergencyWithdraw" | "EmergencyWithdrawEnabled" | "LockPeriodUpdated" | "OwnershipTransferred" | "PenaltyUpdated" | "RewardClaimed" | "RewardRateUpdated" | "Staked" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'claimRewards', values?: undefined): string;
encodeFunctionData(functionFragment: 'earlyWithdrawalPenalty', values?: undefined): string;
encodeFunctionData(functionFragment: 'earned', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyWithdrawEnabled', values?: undefined): string;
encodeFunctionData(functionFragment: 'exit', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundRewards', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPoolInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUserInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastUpdateTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'lockPeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingRewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'poolId', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardPerToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardPerTokenStored', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setEmergencyWithdrawEnabled', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setLockPeriod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPenalty', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRewardRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakingToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalStaked', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'claimRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'earlyWithdrawalPenalty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'earned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdrawEnabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoolInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastUpdateTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardPerToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardPerTokenStored', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEmergencyWithdrawEnabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLockPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPenalty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRewardRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalStaked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace EmergencyWithdrawEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyWithdrawEnabledEvent {
      export type InputTuple = [enabled: boolean];
      export type OutputTuple = [enabled: boolean];
      export interface OutputObject {enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockPeriodUpdatedEvent {
      export type InputTuple = [newLockPeriod: BigNumberish];
      export type OutputTuple = [newLockPeriod: bigint];
      export interface OutputObject {newLockPeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PenaltyUpdatedEvent {
      export type InputTuple = [newPenalty: BigNumberish];
      export type OutputTuple = [newPenalty: bigint];
      export interface OutputObject {newPenalty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardClaimedEvent {
      export type InputTuple = [user: AddressLike, reward: BigNumberish];
      export type OutputTuple = [user: string, reward: bigint];
      export interface OutputObject {user: string, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardRateUpdatedEvent {
      export type InputTuple = [newRate: BigNumberish];
      export type OutputTuple = [newRate: bigint];
      export interface OutputObject {newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, penalty: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, penalty: bigint];
      export interface OutputObject {user: string, amount: bigint, penalty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StakingPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): StakingPool;
    waitForDeployment(): Promise<this>;

    interface: StakingPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claimRewards: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    earlyWithdrawalPenalty: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    earned: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    emergencyWithdrawEnabled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    exit: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    fundRewards: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getPoolInfo: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, boolean] & {_totalStaked: bigint, _rewardRate: bigint, _lockPeriod: bigint, _penalty: bigint, _emergencyEnabled: boolean }],
      'view'
    >
    

    
    getUserInfo: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {stakedAmount: bigint, rewardsClaimed: bigint, lockEndTime: bigint, firstStakeTime: bigint }],
      'view'
    >
    

    
    lastUpdateTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lockPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingRewards: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    poolId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewardPerToken: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewardPerTokenStored: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewardRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewardToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setEmergencyWithdrawEnabled: TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setLockPeriod: TypedContractMethod<
      [newLockPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPenalty: TypedContractMethod<
      [newPenalty: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRewardRate: TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakingToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalStaked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userInfo: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {stakedAmount: bigint, rewardDebt: bigint, rewardsClaimed: bigint, lockEndTime: bigint, firstStakeTime: bigint }],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claimRewards'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'earlyWithdrawalPenalty'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'earned'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyWithdrawEnabled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'exit'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundRewards'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPoolInfo'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, boolean] & {_totalStaked: bigint, _rewardRate: bigint, _lockPeriod: bigint, _penalty: bigint, _emergencyEnabled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getUserInfo'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {stakedAmount: bigint, rewardsClaimed: bigint, lockEndTime: bigint, firstStakeTime: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'lastUpdateTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingRewards'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'poolId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewardPerToken'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewardPerTokenStored'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewardRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewardToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setEmergencyWithdrawEnabled'): TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLockPeriod'): TypedContractMethod<
      [newLockPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPenalty'): TypedContractMethod<
      [newPenalty: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRewardRate'): TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakingToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalStaked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userInfo'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {stakedAmount: bigint, rewardDebt: bigint, rewardsClaimed: bigint, lockEndTime: bigint, firstStakeTime: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EmergencyWithdraw'): TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
getEvent(key: 'EmergencyWithdrawEnabled'): TypedContractEvent<EmergencyWithdrawEnabledEvent.InputTuple, EmergencyWithdrawEnabledEvent.OutputTuple, EmergencyWithdrawEnabledEvent.OutputObject>;
getEvent(key: 'LockPeriodUpdated'): TypedContractEvent<LockPeriodUpdatedEvent.InputTuple, LockPeriodUpdatedEvent.OutputTuple, LockPeriodUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PenaltyUpdated'): TypedContractEvent<PenaltyUpdatedEvent.InputTuple, PenaltyUpdatedEvent.OutputTuple, PenaltyUpdatedEvent.OutputObject>;
getEvent(key: 'RewardClaimed'): TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
getEvent(key: 'RewardRateUpdated'): TypedContractEvent<RewardRateUpdatedEvent.InputTuple, RewardRateUpdatedEvent.OutputTuple, RewardRateUpdatedEvent.OutputObject>;
getEvent(key: 'Staked'): TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'EmergencyWithdraw(address,uint256)': TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
      EmergencyWithdraw: TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
    

      'EmergencyWithdrawEnabled(bool)': TypedContractEvent<EmergencyWithdrawEnabledEvent.InputTuple, EmergencyWithdrawEnabledEvent.OutputTuple, EmergencyWithdrawEnabledEvent.OutputObject>;
      EmergencyWithdrawEnabled: TypedContractEvent<EmergencyWithdrawEnabledEvent.InputTuple, EmergencyWithdrawEnabledEvent.OutputTuple, EmergencyWithdrawEnabledEvent.OutputObject>;
    

      'LockPeriodUpdated(uint256)': TypedContractEvent<LockPeriodUpdatedEvent.InputTuple, LockPeriodUpdatedEvent.OutputTuple, LockPeriodUpdatedEvent.OutputObject>;
      LockPeriodUpdated: TypedContractEvent<LockPeriodUpdatedEvent.InputTuple, LockPeriodUpdatedEvent.OutputTuple, LockPeriodUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PenaltyUpdated(uint256)': TypedContractEvent<PenaltyUpdatedEvent.InputTuple, PenaltyUpdatedEvent.OutputTuple, PenaltyUpdatedEvent.OutputObject>;
      PenaltyUpdated: TypedContractEvent<PenaltyUpdatedEvent.InputTuple, PenaltyUpdatedEvent.OutputTuple, PenaltyUpdatedEvent.OutputObject>;
    

      'RewardClaimed(address,uint256)': TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
      RewardClaimed: TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
    

      'RewardRateUpdated(uint256)': TypedContractEvent<RewardRateUpdatedEvent.InputTuple, RewardRateUpdatedEvent.OutputTuple, RewardRateUpdatedEvent.OutputObject>;
      RewardRateUpdated: TypedContractEvent<RewardRateUpdatedEvent.InputTuple, RewardRateUpdatedEvent.OutputTuple, RewardRateUpdatedEvent.OutputObject>;
    

      'Staked(address,uint256)': TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
      Staked: TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
    

      'Withdrawn(address,uint256,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }