/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface EscrowInterface extends Interface {
    getFunction(nameOrSignature: "buyerInitialAccount" | "buyerStatMapping" | "deliverGoods" | "deposit" | "locktime" | "receivedGoods" | "refundBuyer" | "releaseFunds"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'buyerInitialAccount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'buyerStatMapping', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deliverGoods', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'locktime', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'receivedGoods', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundBuyer', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseFunds', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buyerInitialAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyerStatMapping', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deliverGoods', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'locktime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receivedGoods', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundBuyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
  }

  

  export interface Escrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow;
    waitForDeployment(): Promise<this>;

    interface: EscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyerInitialAccount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    buyerStatMapping: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    deliverGoods: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    locktime: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    receivedGoods: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    refundBuyer: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    releaseFunds: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyerInitialAccount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyerStatMapping'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deliverGoods'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'locktime'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'receivedGoods'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refundBuyer'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }