/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface EscrowFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createEscrow" | "identifier"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'identifier', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'identifier', data: BytesLike): Result;
  }

  

  export interface EscrowFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowFactory;
    waitForDeployment(): Promise<this>;

    interface: EscrowFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createEscrow: TypedContractMethod<
      [_seller: AddressLike, _buyer: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    identifier: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [_seller: AddressLike, _buyer: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'identifier'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }