/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from './ERC20.sol/index.js';
export type { erc20Sol };
import type * as rewardTokenSol from './RewardToken.sol/index.js';
export type { rewardTokenSol };
import type * as stakingTokenSol from './StakingToken.sol/index.js';
export type { stakingTokenSol };