/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingPoolSol from './StakingPool.sol/index.js';
export type { stakingPoolSol };
import type * as token from './token/index.js';
export type { token };
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export type { IERC20Extended } from './StakingPool.sol/IERC20Extended.js';
export { IERC20Extended__factory } from './factories/StakingPool.sol/IERC20Extended__factory.js';
export type { Ownable } from './StakingPool.sol/Ownable.js';
export { Ownable__factory } from './factories/StakingPool.sol/Ownable__factory.js';
export type { StakingPool } from './StakingPool.sol/StakingPool.js';
export { StakingPool__factory } from './factories/StakingPool.sol/StakingPool__factory.js';
export type { ERC20 } from './token/ERC20.sol/ERC20.js';
export { ERC20__factory } from './factories/token/ERC20.sol/ERC20__factory.js';
export type { IERC20 } from './token/ERC20.sol/IERC20.js';
export { IERC20__factory } from './factories/token/ERC20.sol/IERC20__factory.js';
export type { RewardToken } from './token/RewardToken.sol/RewardToken.js';
export { RewardToken__factory } from './factories/token/RewardToken.sol/RewardToken__factory.js';
export type { StakingToken } from './token/StakingToken.sol/StakingToken.js';
export { StakingToken__factory } from './factories/token/StakingToken.sol/StakingToken__factory.js';