/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from './ERC20.sol/index.js';
export * as rewardTokenSol from './RewardToken.sol/index.js';
export * as stakingTokenSol from './StakingToken.sol/index.js';