/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface CrowdFundingInterface extends Interface {
    getFunction(nameOrSignature: "contribute" | "contributions" | "deadline" | "goal" | "owner" | "totalFunds" | "withdrawFunds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContributionReceived" | "FundsWithdrawn" | "GoalReached"): EventFragment;

    encodeFunctionData(functionFragment: 'contribute', values?: undefined): string;
encodeFunctionData(functionFragment: 'contributions', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'goal', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalFunds', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawFunds', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'goal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFunds', data: BytesLike): Result;
  }

  
    export namespace ContributionReceivedEvent {
      export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [contributor: string, amount: bigint];
      export interface OutputObject {contributor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsWithdrawnEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GoalReachedEvent {
      export type InputTuple = [totalFunds: BigNumberish];
      export type OutputTuple = [totalFunds: bigint];
      export interface OutputObject {totalFunds: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CrowdFunding extends BaseContract {
    
    connect(runner?: ContractRunner | null): CrowdFunding;
    waitForDeployment(): Promise<this>;

    interface: CrowdFundingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    contribute: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    deadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    goal: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalFunds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdrawFunds: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'goal'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalFunds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFunds'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContributionReceived'): TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
getEvent(key: 'FundsWithdrawn'): TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
getEvent(key: 'GoalReached'): TypedContractEvent<GoalReachedEvent.InputTuple, GoalReachedEvent.OutputTuple, GoalReachedEvent.OutputObject>;

    filters: {
      
      'ContributionReceived(address,uint256)': TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
      ContributionReceived: TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
    

      'FundsWithdrawn(address,uint256)': TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
      FundsWithdrawn: TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
    

      'GoalReached(uint256)': TypedContractEvent<GoalReachedEvent.InputTuple, GoalReachedEvent.OutputTuple, GoalReachedEvent.OutputObject>;
      GoalReached: TypedContractEvent<GoalReachedEvent.InputTuple, GoalReachedEvent.OutputTuple, GoalReachedEvent.OutputObject>;
    
    };
  }