/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AverageInterface extends Interface {
    getFunction(nameOrSignature: "add" | "avergae"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'add', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'avergae', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'add', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'avergae', data: BytesLike): Result;
  }

  

  export interface Average extends BaseContract {
    
    connect(runner?: ContractRunner | null): Average;
    waitForDeployment(): Promise<this>;

    interface: AverageInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    add: TypedContractMethod<
      [a: BigNumberish, b: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    avergae: TypedContractMethod<
      [a: BigNumberish, b: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'add'): TypedContractMethod<
      [a: BigNumberish, b: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'avergae'): TypedContractMethod<
      [a: BigNumberish, b: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }