/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { Add, AddInterface } from "../../Todo.sol/Add.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "a",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "b",
        "type": "uint256"
      }
    ],
    "name": "add",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506101aa8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063771602f71461002d575b5f5ffd5b610047600480360381019061004291906100ae565b61005d565b60405161005491906100fb565b60405180910390f35b5f5f828461006b9190610141565b90508091505092915050565b5f5ffd5b5f819050919050565b61008d8161007b565b8114610097575f5ffd5b50565b5f813590506100a881610084565b92915050565b5f5f604083850312156100c4576100c3610077565b5b5f6100d18582860161009a565b92505060206100e28582860161009a565b9150509250929050565b6100f58161007b565b82525050565b5f60208201905061010e5f8301846100ec565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f61014b8261007b565b91506101568361007b565b925082820190508082111561016e5761016d610114565b5b9291505056fea2646970667358221220bf07618491952e9faa1928f212e3e0be63f7d151450001e3e484fc6bd57baeaf64736f6c634300081c0033";

  
      type AddConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: AddConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Add__factory extends ContractFactory {
    
      constructor(...args: AddConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Add & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Add__factory {
      return super.connect(runner) as Add__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): AddInterface {
      return new Interface(_abi) as AddInterface;
    }
    
    override attach(address: string | Addressable): Add {
      return super.attach(address) as Add;
    }
  static connect(address: string, runner?: ContractRunner | null): Add {
      return new Contract(address, _abi, runner) as unknown as Add;
    }
  }

  
  