/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { Average, AverageInterface } from "../../Todo.sol/Average.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "a",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "b",
        "type": "uint256"
      }
    ],
    "name": "add",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "a",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "b",
        "type": "uint256"
      }
    ],
    "name": "avergae",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506101ec8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c8063771602f714610038578063eb76cf6c14610068575b5f5ffd5b610052600480360381019061004d91906100f0565b610098565b60405161005f919061013d565b60405180910390f35b610082600480360381019061007d91906100f0565b6100b2565b60405161008f919061013d565b60405180910390f35b5f5f82846100a69190610183565b90508091505092915050565b5f92915050565b5f5ffd5b5f819050919050565b6100cf816100bd565b81146100d9575f5ffd5b50565b5f813590506100ea816100c6565b92915050565b5f5f60408385031215610106576101056100b9565b5b5f610113858286016100dc565b9250506020610124858286016100dc565b9150509250929050565b610137816100bd565b82525050565b5f6020820190506101505f83018461012e565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f61018d826100bd565b9150610198836100bd565b92508282019050808211156101b0576101af610156565b5b9291505056fea2646970667358221220bb77e7b712135506ca998735b37dc9590181ba878114c4a98f1eed24dcb0c15264736f6c634300081c0033";

  
      type AverageConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: AverageConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Average__factory extends ContractFactory {
    
      constructor(...args: AverageConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Average & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Average__factory {
      return super.connect(runner) as Average__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): AverageInterface {
      return new Interface(_abi) as AverageInterface;
    }
    
    override attach(address: string | Addressable): Average {
      return super.attach(address) as Average;
    }
  static connect(address: string, runner?: ContractRunner | null): Average {
      return new Contract(address, _abi, runner) as unknown as Average;
    }
  }

  
  